name: 'Internal App Sharing'
description: 'Upload aab/apk to Internal App Sharing on Play Console'
inputs:
  serviceAccountJsonPlainText:
    description: 'The service account json plain text private key file to authorize the upload request'
    required: true 
  packageName:
    description: 'Package name of the application'
    required: true
  apkReleaseFile:
    description: '.apk file path'
    required: false
  aabReleaseFile:
    description: '.aab file path'
    required: false
output:
  url:
    description: 'Link to access app on play store'   
runs:
  using: 'node12'
  main: 'lib/index.js'